// <auto-generated />
namespace Bookify.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PersonInBookFeedback : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PersonInBookFeedback));
        
        string IMigrationMetadata.Id
        {
            get { return "201608221312412_PersonInBookFeedback"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
